### ISSUE TITLE
Error using the commandline tools on raw disk

### ISSUE THREAD

**Issue by mbhatt1** [blackbagtech/sleuthkit-APFS#10]
I have been trying to use the commandline tools on raw spinning disk. I don't think i'm doing it correctly and the help isn't helping. Could you please help me by posting about how to correctly use the tools in this scenario?

**Comment by jtsylve** [comment]
Unfortunately, due to the various caching layers and the copy-on-write nature of APFS, it's not practical to use TSK to analyze live APFS containers and volumes when any volume is mounted read/write.  The effects of smearing are amplified greatly and the super-block objects don't stay valid for more than a few minutes at most.  Sometimes they change between the calls to poolstat to learn the super block number and other calls that require passing that block number as a parameter.

This is an open research problem.
