### ISSUE TITLE
Errors compiling on macOS 10.14.5

### ISSUE THREAD

**Issue by Vorensics** [blackbagtech/sleuthkit-APFS#8]
I tried to compile your Sleuthkit version with APFS support on macOS 10.14.5 today using the following method: ./bootstrap; ./configure; make; sudo make install

The bootstrap and configure commands run well without any errors. Unfortunately the make won't run through. I get the following error messages (only the first error here, posted the full text on pastebin: https://pastebin.com/r52wr3tk)

`In file included from ./../fs/tsk_apfs.hpp:5:
./../fs/../pool/tsk_apfs.hpp:38:14: error: explicitly defaulted move assignment operator is implicitly deleted [-Werror,-Wdefaulted-function-deleted]
  APFSBlock &operator=(APFSBlock &&) = default;
./../fs/../pool/tsk_apfs.hpp:23:19: note: move assignment operator of 'APFSBlock' is implicitly deleted because field '_pool' is of reference type 'const APFSPool &'
  const APFSPool &_pool;
`

Does anybody have a clue what went wrong and/or how to fix it?

**Comment by simsong** [comment]
Use a compiler that isn’t so picky.
Turn off -Werror until it gets fixed.

**Comment by mbhatt1** [comment]
What was said^^

**Comment by jtsylve** [comment]
Hello everyone,

I'm aware of the issues with compiler warnings (and errors due to -Werror) with newer versions of LLVM, and I do have fixes and additional enhancements to the codebase.  However, I've decided that since the upstream APFS integration is in progress, that it wouldn't be wise to maintain an ever-diverging fork.  Instead, I encourage you to check out the apfs branch of the main sleuthkit repo, and I'll be submitting my fixes and enhancements as PR, so they can manage the inevitable conflicts that may arise when trying to merge to their main branch.

Please validate any bugs you have with the current codebase against the apfs branch of the official sleuthkit repository and report them over there as needed.  I'll be checking their issue tracker and submitting fixes.

- Joe
