### ISSUE TITLE
apfs_compat.cpp error when make

### ISSUE THREAD

**Issue by perosurac** [blackbagtech/sleuthkit-APFS#9]
Hi all,

**_System_** : Debian Buster updated and upgraded

When trying to install, bootstrap ok, configure ok, but here is the errors I get when I do a "make" :

> apfs_compat.cpp:926:35: **error**: ‘fs_file’ was not declared in this scope
           if (tsk_fs_attr_set_run(fs_file, fs_attr, NULL, "DECOMP",
                                   ^~~~~~~
apfs_compat.cpp:926:35: note: suggested alternative: ‘tmpfile’
           if (tsk_fs_attr_set_run(fs_file, fs_attr, NULL, "DECOMP",
                                   ^~~~~~~
                                   tmpfile
apfs_compat.cpp:928:35: **error**: ‘HFS_FS_ATTR_ID_DATA’ was not declared in this scope
                                   HFS_FS_ATTR_ID_DATA, 0, 0, 0, 0, 0)) {
                                   ^~~~~~~~~~~~~~~~~~~

Someone an idea how to resolv it ?

Thanks in advance.

**Comment by DannyKielman** [comment]
I'm having exactly the same issue on Ubuntu 18.04. Can't seem to find the error in the code right away...

**Comment by jtsylve** [comment]
Hello everyone,

I'm aware of the issues with compiler warnings (and errors due to -Werror) with newer versions of LLVM, and I do have fixes and additional enhancements to the codebase.  However, I've decided that since the upstream APFS integration is in progress, that it wouldn't be wise to maintain an ever-diverging fork.  Instead, I encourage you to check out the apfs branch of the main sleuthkit repo, and I'll be submitting my fixes and enhancements as PR, so they can manage the inevitable conflicts that may arise when trying to merge to their main branch.

Please validate any bugs you have with the current codebase against the apfs branch of the official sleuthkit repository and report them over there as needed.  I'll be checking their issue tracker and submitting fixes.

- Joe
